name: 🚀 Deploy to PythonAnywhere

on:
  push:
    branches:
      - initial-setup  # This will trigger the deployment when you push to the 'initial-setup' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH and Execute Deployment Script on PythonAnywhere
        env:
          PA_USERNAME: ${{ secrets.PA_USERNAME }}
          PA_PASSWORD: ${{ secrets.PA_PASSWORD }}
        run: |
          # Install sshpass to allow SSH login via password
          sudo apt-get update
          sudo apt-get install -y sshpass

          # SSH into PythonAnywhere and run the deploy.sh script
          # Make sure the deploy.sh script is executable and then run it.
          sshpass -p "$PA_PASSWORD" ssh -o StrictHostKeyChecking=no "$PA_USERNAME@ssh.pythonanywhere.com" "
            chmod +x /home/$PA_USERNAME/deploy.sh && \\
            /home/$PA_USERNAME/deploy.sh
          "
